### ISSUE TITLE
Issue with multi-selection special case

### ISSUE THREAD

**Issue by SamiPirbay** [lesgrieve/paste-indent#1]
It doesn't work if you copy X selections and paste them into exactly X cursor locations.

For example, if you copy 3 lines:
`A`
`B`
`C`
and you paste them in 10 locations, you get `A\nB\nC\n` in each of the 10 locations, for a total of 30 lines. This is fine.

But what if you paste them into exactly 3 locations? It's a special/magic case.
Rather than duplicate `A\nB\nC\n` three times (so a total of 9 lines), you want to paste `A` in the first location, `B` in the second one, and `C` in the third one (so a total of 3 lines.)

**Comment by lesgrieve** [comment]
Thank you for your feedback. I plan to attempt reproduction and resolution of this issue but it may be a month or two before I can look at it.

**Comment by lesgrieve** [comment]
@SamiPirbay I owe you some feedback. I reproduced this problem and tried some different ways to try and fix it. The truth is that getting this special case to work would involve more development than the original development took and I do not plan on addressing this issue. My practice is to use the normal paste function instead of paste-indent when dealing with multiple selections.

**Comment by Whoaa512** [comment]
I would also really appreciate this feature. Do you have a branch where you attempted to fix it? Would be open to looking and maybe contributing back

**Comment by lesgrieve** [comment]
I do not have a branch. I would happily accept a pull request.

**Comment by lesgrieve** [comment]
@SamiPirbay, thanks to @Whoaa512, v0.0.3 has been published with the fix.
